[DEFAULT]
ServerAliveInterval = 45
Compression = yes
CompressionLevel = 9

[mainmotors]
pwm_freq	= 10000
left_pin_a 	= 27
left_pin_b 	= 21
right_pin_a 	= 26
right_pin_b 	= 19
verbose 	= True

[gamepad]
joystickSpeed 		= LEFT-Y
joystickSteering 	= LEFT-X
pollInterval		= 0.1
deadZone		= 0.5
turnMultiplier		= 0.8
steeringDivider		= 2
speedDivider		= 1.25


[audio]
loop			=	False
loop_interval_low	=	10
loop_interval_high	=	30
